[package]
name    = "borealis"
version = "0.1.0"
authors = ["Martin Risell Lilja <martin.risell.lilja@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/martinrlilja/borealis"

[dependencies]
html5ever    = "0.5"
string_cache = "0.2"
